spring.application.name=ident

# -------------------- Perfil / Ambiente --------------------
# Define o perfil ativo
spring.profiles.active=dev

# -------------------- Servidor --------------------
# Porta que a aplicação irá rodar
server.port=8080

# Tempo máximo de inatividade da sessão em segundos (se aplicável)
server.servlet.session.timeout=1800

# -------------------- Segurança / JWT --------------------
# Chave secreta para gerar e validar tokens JWT.
# Pode ser lida de uma variável de ambiente JWT_SECRET
# Se não existir, usa o valor padrão "o-sol-esta-lindo"
api.security.token.secret=@{JWT_SECRET:the-sun-is-beautiful}